apiVersion: skaffold/v1beta12
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: client-image
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
          - src: 'src/**/*.css'
            dest: .
          - src: 'src/**/*.html'
            dest: .
    - image: server-image
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
deploy:
  kubectl:
    manifests:
      - 'k8s/*'